### ISSUE TITLE
Confirmation needed.

### ISSUE THREAD

**Issue by harsha09** [Unbabel/backend-engineering-challenge#10]
Before starting this I'ld like to confirm few things

1. Is the duration in seconds?
2. Past X minutes, is it with respect to current time (when the script is run), or the latest timestamp in the file?

**Comment by bacarini** [comment]
Hi @harsha09 

first of all, thank you for your questions

1) yes, you can consider the duration as seconds
2) get the first timestamp of the events and iterate from it

Looking forward to seeing your code mate
