### ISSUE TITLE
Details/Inputs needed

### ISSUE THREAD

**Issue by NileshMali1** [Unbabel/backend-engineering-challenge#11]
1. If events.json is to be treated literally as JSON file then its formatting is bad since it has multiple root elements, which tempts me to consider its to be treated as text file with each line as a stringified JSON. Please confirm.
2. Unit of duration would add more clarity to data interpretation here. Perhaps, rename "duration" field to "duration_in_{unit}"? Please clarify what duration field unit is for now.
3. Regarding past X minutes- "from timestamp" information is not given. Could I consider from most recent events' timestamp from events.json file?

**Comment by bacarini** [comment]
Hi @NileshMali1 

first of all, thank you for your questions 

1) yes you are right it is a text file with stringified JSON

2) you can consider the duration as seconds

3) please consider the latest timestamp from the file

Thank you for the suggestions
Looking forward to seeing your code mate
