### ISSUE TITLE
I would like to get cleared about few unclear things..

### ISSUE THREAD

**Issue by HiranD** [Unbabel/backend-engineering-challenge#3]
I would like to get cleared about few unclear things in the challenge. 

1. I think following line should be "we deal with".
**At Unbabel we deal we a lot of translation data.**

2. Also the following "25,5" should be "25.5"

_{"date": "2018-12-26 18:15:00", "average_delivery_time": 20}
{"date": "2018-12-26 18:16:00", "average_delivery_time": 25,5}
{"date": "2018-12-26 18:17:00", "average_delivery_time": 25,5}_

3. "Feel free to, in your solution, include some your considerations while doing this challenge." <- is this mean to comment on my coding choices. Like why I do that, this way..  Is it?

Please let me know.

**Comment by bacarini** [comment]
Hi @HiranD 

First of all, thank you for sending us these considerations.

The first and the second items, you are correct and we will change it. As for the last one if you want to include something that we didn't describe it is up to you and it is part of the challenge.

Anyway, these items shouldn't be a blocker.

Hope to see your challenge soon.

Cheers
