### ISSUE TITLE
Reading events, acceptable solutions.

### ISSUE THREAD

**Issue by danaidh** [Unbabel/backend-engineering-challenge#32]
Hi! I'm thinking in two approches that I would like to persue for this challenge, and I'll like to know if I can do both of them by creating two solutions, or any of the approches would be acceptable for you guys and I can create a single solution.

One: A CLI application that reads the events from a json file and generates an aggregated output file.
Two: A CLI application that listen to the events from a kafka topic and writes the aggregated output into a second topic.

Best regards!

**Comment by JoaoVasques** [comment]
Hi @danaidh !

Thanks for reaching out. My personal suggestion is to go for the first option and design it in a way that makes extending it to something like option easy.

Hope this answers your questions.

Bets,
JV
