### ISSUE TITLE
Seeking clarity

### ISSUE THREAD

**Issue by oiclid** [Unbabel/backend-engineering-challenge#8]
I would like to clarify a couple of things: 
1. What time unit is the duration in? The default mico-seconds or something else?
2. Do we get a test events.json file, or should we just use the example input file?

And finally, I think I may have found a typo. I think "we're instered in calculating," should be "we're interested in calculating."

**Comment by bacarini** [comment]
Hi @oiclid 

first of all, thank you for your questions and also for catching the typo we will fix it.

as for your questions

1) you can consider the duration as seconds

2) We won't send any file, you can create your own or use the example input. Once you submit your challenge we will run your code with a couple of samples we have here to validate it

Please lets us know if there is anything else.
Looking forward to seeing your code mate
